apiVersion: apps/v1
kind: Deployment
metadata:
  name: kolabajamysql
spec:
  selector:
    matchLabels:
      app: kolabajamysql
  replicas: 1
  template:
    metadata:
      labels:
        app: kolabajamysql
    spec:
      containers:
        - name: kolabajamysql
          image: mysql:8.0.29
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: "kolabaja"
            - name: MYSQL_USER
              value: "test"
            - name: MYSQL_PASSWORD
              value: "1234"
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"