apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: kolabajamysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
